apiVersion: v1
kind: Secret
metadata:
  name: db
type: Opaque
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_URL: "postgres://postgres:postgres@db:5432/postgres"
