---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{$.Values.logefrei.namespace}}
  name: background
  labels:
    app: background
    version: {{ $.Chart.AppVersion }}
spec:
  replicas: {{$.Values.logefrei.back.replicas}}
  selector:
    matchLabels:
      app: background
  template:
    metadata:
      labels:
        app: background
    spec:
      initContainers:
        - name: wait-for-migration
          image: bitnami/kubectl
          command: ['sh', '-c', 'until kubectl get job migrate-job -n {{ $.Values.logefrei.namespace }} -o jsonpath="{.status.succeeded}" | grep 1; do echo waiting for migration job to complete; sleep 5; done']
      containers:
        - name: background
          image: "{{ $.Values.logefrei.back.image.repository }}-full:{{ $.Values.logefrei.back.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
          command: ["bun", "run", "src/services/background/index.ts"]