apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  ports:
    - port: 3000
  selector:
    app: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      initContainers:
        - name: wait-for-kruskal-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -v -w30 kruskal 3000; do echo waiting for kruskal service; sleep 5; done",
            ]
        - name: wait-for-dijkstra-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -v -w30 dijkstra 3000; do echo waiting for dijkstra service; sleep 5; done",
            ]
        - name: wait-for-canvas-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -v -w30 canvas 3000; do echo waiting for canvas service; sleep 5; done",
            ]
        - name: wait-for-data-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -v -w30 data 3000; do echo waiting for data service; sleep 5; done",
            ]
      containers:
        - name: proxy
          image: ghcr.io/efrei-lsi-2025/metroboulotdodo-back:k8s
          ports:
            - containerPort: 3000
          command: ["npm"]
          args: ["run", "start:proxy"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  routes:
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: proxy
          port: 3000
