---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{$.Values.logefrei.namespace}}
  name: front
  labels:
    app: front
    version: {{ $.Chart.AppVersion }}
spec:
  replicas: {{$.Values.logefrei.front.replicas}}
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: "{{ $.Values.logefrei.front.image.repository }}:{{ $.Values.logefrei.front.image.tag }}"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{$.Values.logefrei.namespace}}
  name: front
  labels:
    app: front
    version: {{ $.Chart.AppVersion }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: front
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: {{$.Values.logefrei.namespace}}
  name: front
  labels:
    app: front
    version: {{ $.Chart.AppVersion }}
spec:
  routes:
    - match: Host(`{{ $.Values.logefrei.host }}`)
      kind: Rule
      services:
        - name: front
          port: 3000
      middlewares:
        - name: ak-outpost-authentik-embedded-outpost
