---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Values.logefrei.namespace }}
  name: {{ $.Values.logefrei.database.secret }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.logefrei.database.database | b64enc }}
  POSTGRES_USER: {{ .Values.logefrei.database.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.logefrei.database.password | b64enc }}
  DATABASE_URL: {{ printf "postgres://%s:%s@postgres:5432/%s" .Values.logefrei.database.user .Values.logefrei.database.password .Values.logefrei.database.database | b64enc }}