name: Build & push

on:
  push:
    branches:
      - 'master'
      - 'k8s'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image: ghcr.io/efrei-lsi-2025/metroboulotdodo-front
            context: ./images/front
            dockerfile: ./images/front/Dockerfile
          - image: ghcr.io/efrei-lsi-2025/metroboulotdodo-back
            context: .
            dockerfile: ./Dockerfile
          - image: ghcr.io/efrei-lsi-2025/metroboulotdodo-db
            context: ./images/db
            dockerfile: ./images/db/Dockerfile
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
